### ISSUE TITLE
mission tiem is broken.

### ISSUE THREAD

**Issue by SgtxRootbeer** [Pascal125/Faster-Than-Lizard-13#67]
#63 is broken, mission time is still at 2 hours, give or take a few.

**Comment by EvilJackCarver** [comment]
Refuting: Last night we got another mission after one cleared 3 and a quarter hours in.

**Comment by SgtxRootbeer** [comment]
![snibby](https://cloud.githubusercontent.com/assets/22112255/22129328/21ca9648-de5a-11e6-988c-03addc975a24.PNG)
keep in mind, that we got our return home objective about 40 minutes previously. i just didnt see your comment until now.

**Comment by EvilJackCarver** [comment]
Okay, I see what's going on then.

Technically, this is functioning as intended, because in ` code/controllers/subsystem/starmap.dm:36` it defines the weight of the objectives there. Further on down at line 184 is where the game decreases the weight - if the possible weight is zero, it is removed from the list of possible objectives. At the top line of the argument the line prior, if all the objectives are removed, the 'if' check fails and goes to 'go home' mode:

```DM
		if(objective_types.len && world.time < 162000)
			var/objectivetype = pickweight(objective_types)
			objective_types[objectivetype]--
			if(objective_types[objectivetype] <= 0)
				objective_types -= objectivetype
			O = new objectivetype
		else
			O = new /datum/objective/ftl/gohome```

@Pascal125
